name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'  # Explicit Ruby version for CI
          bundler-cache: true
      - name: Make bin/ scripts executable
        run: chmod +x bin/*
      - name: Scan for Rails vulnerabilities
        run: bin/brakeman --no-pager

  scan_js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'  # Explicit Ruby version for CI
          bundler-cache: true
      - name: Make bin/ scripts executable
        run: chmod +x bin/*
      - name: Audit JavaScript dependencies
        run: bin/importmap audit

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'  # Explicit Ruby version for CI
          bundler-cache: true
      - name: Make bin/ scripts executable
        run: chmod +x bin/*
      - name: Run Rubocop
        run: bin/rubocop -f github

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y google-chrome-stable curl libjemalloc2 libvips sqlite3
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'  # Explicit Ruby version for CI
          bundler-cache: true
      - name: Make bin/ scripts executable
        run: chmod +x bin/*
      - name: Prepare test database
        env:
          RAILS_ENV: test
        run: bin/rails db:test:prepare
      - name: Run all tests
        env:
          RAILS_ENV: test
        run: bin/rails test
      - name: Upload screenshots from failed tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore
