name: Deploy to EC2

on:
  push:
    branches:
        # Trigger deployment on push to main branch
      - main
  # Allow manual trigger of the workflow
  workflow_dispatch:

jobs:
  deploy:
    # Use Ubuntu runner for GitHub Actions
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Ruby (you can change the Ruby version as needed)
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # Specify the Ruby version used by your app
          ruby-version: '3.3.5'

      # Install dependencies
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      # Set up SSH access to EC2 instance
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/RSA.pem
          chmod 600 ~/.ssh/RSA.pem
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # SSH into EC2 and navigate to Rails app
      - name: SSH into EC2 and deploy app
        env:
          HOST: ${{ secrets.EC2_HOST }}
        run: |
          ssh -i ~/.ssh/RSA.pem ubuntu@$HOST << 'EOF'
            cd ~/Article_Management_System_Rails_App
            # Pull the latest code
            git pull origin main
            # Install any new dependencies
            bundle install
            # Restart the Rails app server
            rails s -d
          EOF
