name: Deploy to EC2

on:
  push:
    branches:
      # Trigger deployment on push to main branch
      - main
      # Allow manual trigger of the workflow
  workflow_dispatch:

jobs:
  deploy:
    # Use Ubuntu runner for GitHub Actions
    runs-on: ubuntu-latest

    

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Ruby (you can change the Ruby version as needed)
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # Specify the Ruby version used by your app
          ruby-version: '3.3.5'

      # Install dependencies
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      # Set up SSH access to EC2 instance
      - name: Set up SSH
        run: |
          # Create .ssh directory if it doesn’t exist
          mkdir -p ~/.ssh

          # Write the SSH private key directly to RSA.pem and ensure no extra characters
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/RSA.pem

          # Set strict permissions on the private key file to ensure it's not accessible by others
          chmod 600 ~/.ssh/RSA.pem

          # Verify key format by counting lines (typically 16-20 for RSA keys)
          cat ~/.ssh/RSA.pem | wc -l  # Verify key lines

          # Use ssh-keyscan to add the host to known_hosts to avoid host verification prompts
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

          # Check permissions of .ssh directory to confirm RSA.pem has 600 permissions
          ls -la ~/.ssh  # This should show RSA.pem with 600 permissions

          # Test SSH connection to confirm everything works
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/RSA.pem
          cat ~/.ssh/RSA.pem | wc -l

      # Test SSH Connection to ensure access to the EC2 instance works
      - name: Test SSH Connection
        env:
          HOST: ${{ secrets.EC2_HOST }}
        run: |
          ssh -i ~/.ssh/RSA.pem -o StrictHostKeyChecking=no ubuntu@$HOST "echo 'Connection successful'"

      # Deploy to EC2 by pulling the latest code and restarting Rails server
      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
        run: |
          ssh -i ~/.ssh/RSA.pem ubuntu@$HOST << 'EOF'
            cd ~/Article_Management_System_Rails_App
            # Pull the latest code
            git pull origin main
            # Install any new dependencies
            bundle install
            # Restart the Rails app server
            rails s -d
          EOF
